vision:
    build: app/
    command: gin -a=8080 -b="pay"
    working_dir: /go/src/github.com/paked/pay/
    expose: 
        - "3000"
    volumes:
        - ./app/:/go/src/github.com/paked/pay
        - ./models/:/go/src/github.com/paked/pay/models
        - ./crypto/:/crypto
    links:
        - jarvis
    env_file: .env

mystique:
    restart: always
    build: nginx/
    ports:
        - "80:80"
    volumes:
        - ./static/:/app
    links: 
        - vision
jarvis:
    image: postgres
